import enum
# Action = enum.Enum('Action', 'INVADE DENOUNCE MAKE_FRIEND SUPPLY CONSTRUCT EXTORT POLICY')
Action = enum.Enum('Action', 'INVADE DENOUNCE MAKE_FRIEND SUPPLY CONSTRUCT POLICY PRODUCE')
INTERACT_ACTIONS = [Action[a] for a in 'INVADE DENOUNCE MAKE_FRIEND SUPPLY'.split()]
SELF_ACTIONS = [Action[a] for a in 'CONSTRUCT POLICY PRODUCE'.split()]

